# Generated by Django 6.0.3 on 2026-03-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0002_alter_produto_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "link_destino",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
