# Generated by Django 6.0.3 on 2026-03-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0003_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=80, null=True)),
                ("codigo", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
