# Generated by Django 6.0.3 on 2026-03-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0005_alter_itemestoque_cor"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tipo",
            name="slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
