# Generated by Django 6.0.3 on 2026-03-20 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0006_categoria_slug_tipo_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_pagamento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status_pagamento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("data_pagamento", models.DateTimeField(blank=True, null=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loja.pedido",
                    ),
                ),
            ],
        ),
    ]
