# Generated by Django 6.0.3 on 2026-03-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0007_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="aprovado",
            field=models.BooleanField(default=False),
        ),
    ]
